### ISSUE TITLE
More restrictive main bower entry?

### ISSUE THREAD

**Issue by gdcohan** [HubSpot/vex#113]
Hey--

What do you think about changing the main entry of bower.json to be something like:

```
"main": [
  "js/vex.min.js",
  "css/vex.css"
]
```

so that people aren't getting a ton of js and css files by default?

**Comment by adamschwartz** [comment]
According to https://github.com/bower/bower.json-spec, we should not be including minified files. So it is probably the case that something should be done as we are including them now.

While it’s true that `vex.js` and `vex.css` are the minimal JS/CSS in order to use `vex.open` and related APIs, you won’t get any of the vex dialog (alert/confirm/prompt) functionality or themes.

If you check out the [__Including__ section in the docs](http://github.hubspot.com/vex/) you’ll see what is really necessary to get the functionality most people are looking for. With that in mind I could see something like this:

```
"main": [
  "js/vex.js",
  "js/vex.dialog.js",
  "css/vex.css",
  "css/vex-theme-default.css"
]
```

However, it would be somewhat arbitrarily promoting the default theme over the others. So I’d be more inclined to do something like this:

```
"main": [
  "js/vex.js",
  "js/vex.dialog.js",
  "css/vex.css",
  "css/*.css"
]
```

-----

One thing that would help me understand the problem a little better is understanding what you mean by “so that people aren't getting a ton of js and css files by default?”. As far as I know (from looking at the Bower spec), `main` doesn’t determine which files you get, but only which ones are listed by a few Bower tools:

> While Bower does not directly use these files, they are listed with the commands bower list --json and bower list --paths, so they can be used by build tools.

Do you use `bower list` and is this the issue you’re having?

**Comment by gdcohan** [comment]
Ya you're right about not having minified assets. But ya, I'm referring specifically to some build tools like wiredep that use the main entry and require manual overrides in order to avoid all the additional css files. I hear what you're saying about favoring the default theme, but that seems more reasonable to me than automatically including every other theme. 

Somewhat unrelated, but my experience has also been that bower packages don't have any uncompiled assets in them (like coffeescript files).

**Comment by bbatliner** [comment]
I'm not sure how bower works or if anyone is still using it with vex. Please make a new issue if this is still a concern. Thanks for using vex!
