### ISSUE TITLE
Release vex@3.0.0

### ISSUE THREAD

**Issue by geekjuice** [HubSpot/vex#163]
Reminder to release `vex@3.0.0` as `latest` on `npm` potentially by the end of the week (Aug 12, 2016). As far as I can tell, the beta release was mostly a precaution for the major release, but I think it's safe to take it out of beta sooner than later and just iterate when needed.

@timmfin @adamschwartz @bbatliner

**Comment by bbatliner** [comment]
Ping - are we good to release?

**Comment by geekjuice** [comment]
Hey @bbatliner, I think the only thing might worth considering https://github.com/HubSpot/vex/issues/165. Once we figure out a course of action for that, I'll be more than happy to help take this out of beta 🍻

**Comment by lgdexter** [comment]
@geekjuice looking forward to the release, currently not working with Webpack. Thanks guys.

**Comment by markstos** [comment]
I put the 3.0.0 beta into production after doing a reality check with Edge 14, Firefox 48, Safari 9.1, and IE 10 and 11. Basic "confirm" functionality was tested. It's live on about 40 of our domains now. If something is broken, I expect we'll find out soon now. 

One more bit of feedback while it is beta: I understand it to be best practice to version file names.  So, if are using vex-3.0.js, you can cache that with a long cache time, and then when in it's time to upgrade to vex-3.1.js, you can can update URLs to point to the new URL, which will immediately bust the cache.  Without the unique-per-version URLs, you either can't safely take advantage of caching, or you risk people loading the wrong version during an upgrade. 

So the suggestion is to consider:

   * updating the build process so that the build products in `./dist` contain a version in the file name.
   * Where possible, update generated documentation to reflect the currention version in file names instead of generic `vex.js` mentions with no version in the name.

Immediately, this may help in the Vex 1 -> Vex 3 upgrade process. If users follow the recommended new naming scheme, that will insure their file names change as part of the upgrade, and the end users will be sure load the latest version, avoiding possibly weird transition problems where there might be a mismatch between the calling code and the vex library.

**Comment by geekjuice** [comment]
Hey @markstos,

I think those are great points, but I (personally) might push back on adding the version to the filename. I haven't seen that pattern used recently so I'm not really sure it's really a best practice anymore (I may be wrong). Most projects either use a CDN (that includes the version for you) or have a custom build system that takes care of most of the issues you described (file renaming, bundling, etc). 

As for your last point about the upgrade process, if they are pointing straight to the `dist` directory on GitHub, that's definitely bad practice so it would probably be in their best interest to move off that pattern and use a CDN for providing the library. But the recent upgrade restructured the directories so they would still be pointing to an non-existent filepath.

Having said all this though, I'll defer to @bbatliner to make the final call. One thing we do in other projects is to add the version as a header in the file. I would consider adding that (if it doesn't already exist) since it does help determine what the version is being used.

**Comment by markstos** [comment]
I'm pretty sure there are also a lot of projects that don't use a CDN, because they they are too small to bother, and also don't use a build system that handles this. Our project is fairly modern, based on Angular and uses "gulp" for a build system, yet after some failed attempts with bower, we end up just manually copying third-party libraries into place. 

I wasn't suggesting that people would link to the "dist" directory on Github-- a bad idea-- but rather that they would:
  
  * Simply copy the files in the "dist" directory into their own tree
  * Exactly copy/paste/emulate the example snippets in the documentation, which don't include any version numbers.

Adding the version number into the header during the build process would also be welcome addition. 

When I'm digging through our `js/libs` directory and find a file name that is not versioned, having the version present inside the file is *very* helpful to help me determine which version we are running.

**Comment by bbatliner** [comment]
Version numbers are in the header of the minified files. Versions in the filenames isn't difficult to change, but adds additional complexity because the `package.json` would need to be updated to point to the latest versioned filename with each build/release. What we have now is best, in my opinion.
