### ISSUE TITLE
Multi line text with vex.dialog.alert() ?

### ISSUE THREAD

**Issue by maxelliz** [HubSpot/vex#230]
Hello,
I want to fire an alert with multi-line text using vex.dialog.alert() but "\n" seems to be useless, same for multiple spaces between two sentences. Any tips to succeed ?
that's working : alert("Stage done"+ "\n"+ "Start the next one now ?");
that's not : vex.dialog.alert("Stage done"+ "\n"+ "Start the next one now ?");
Have a nice day :)

**Comment by bbatliner** [comment]
Here's a version that will work:

```javascript
vex.dialog.alert({ unsafeMessage: 'Stage done<br>Start the next one now ?' })
```

However, you made a great point - the default browser `alert` works with the new line, and vex, aiming to be a drop-in replacement for that, doesn't.

This happens because the string you pass to vex dialog is wrapped inside of a `div`. To have the newline character show up as a new line, we need to add `white-space: pre` to the styling of that div. I'm hesitant to make the change immediately because it will affect how the text renders in a significant way. What do you think?

**Comment by maxelliz** [comment]
Thanks for the answer ! It's perfect like that. No need to change something when unsafeMessage + <br> is doing the trick
