### ISSUE TITLE
Vex with dialog opened as hidden, shown after a delay

### ISSUE THREAD

**Issue by ux-engineer** [HubSpot/vex#53]
For embedding a chat window on a modal, that chat requires the modal to be rendered right on pageload yet I want the modal to be displayed after a delay. How can this be achieved?

**Comment by Pumppa** [comment]
Greetings, I myself ran into the same kind of issue. In essence I'd like to delay the opening of the vex dialog by a set amount of time. This without dependencies can easily be achieved by using setTimeout. How ever I have another piece of javascript parsing the document for the vex html output. If entire excution of vex is delayed the parsing has passed (jQuery(document).ready), returned a null field and everything falls apart. On the other hand using the display / visibility trick shown here causes another problem by freezing the browser window entirely until the time has passed and vex dialog is visible and has been cancelled. 

Is there a way of getting the html in place and properly delaying the vex.dialog.open so that the browser is not frozen while the dialog is hidden?
