### ISSUE TITLE
"vex not defined" when implemeting using requireJS

### ISSUE THREAD

**Issue by bengsfort** [HubSpot/vex#60]
Working on a web app and trying to implement Vex Dialogs using requireJS. Everything compiles fine, however whenever I open the page all I get is a reference error saying vex is not defined. Have tried using the minified and unminified files, vex.dialog.js and vex.js.

In my gruntfile under paths:
jquery : 'extra/jquery-2.1.1.min',
. . . .
vex : 'extra/vex',

In my main.js, the file that calls it:
require([ "system", "ui", "jquery", "vex" ]);

Just to test it working I have the standard confirm demo pasted in, but continue getting the reference error. Is there something I'm just not doing correctly in terms of requireJS?

**Comment by dianafaye17** [comment]
I'm having the same issue.

**Comment by ferhtgoldaraz** [comment]
I think this is related to #141, and the fix could be to change "vex" to "vex-js" in the array of `define` dependencies as has been suggested on that issue: https://github.com/HubSpot/vex/issues/141#issuecomment-175163079

It worked for me, my `define` implementation is provided by webpack.

**Comment by markstos** [comment]
Note there are big changes planned in the next version of vex is #160 you are encouraged to review the new changes and see if ti would meet your needs here.

**Comment by bbatliner** [comment]
Hey all! #160 is merged and I want to make sure your problem is fixed. vex is now built with browserify's standalone option, which should make it compatible with all module systems, including requirejs and AMD.

If you don't mind, can you try the latest files ([download from here](https://github.com/HubSpot/vex/tree/master/dist) or `npm install vex-js vex-dialog`) and let me know if they're working? Thanks!

**Comment by bbatliner** [comment]
Assuming this worked fine :)
